import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const playerRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(playerRoot, "../..");
const source = path.join(playerRoot, "dist/element.js");
const compatSource = path.join(playerRoot, "dist/compat.js");
const targetDir = path.join(repoRoot, "apps/web/public/vendor/player");
const target = path.join(targetDir, "element.js");
const compatTarget = path.join(targetDir, "compat.js");
const versionFile = path.join(
  repoRoot,
  "apps/web/lib/player/player-asset.generated.ts",
);

if (!fs.existsSync(source)) {
  console.error("[copy-vendor] missing dist/element.js — run build first");
  process.exit(1);
}

const code = fs.readFileSync(source, "utf8");
const compatCode = fs.existsSync(compatSource)
  ? fs.readFileSync(compatSource, "utf8")
  : null;
fs.mkdirSync(targetDir, { recursive: true });
fs.writeFileSync(target, code);

if (compatCode) {
  fs.writeFileSync(compatTarget, compatCode);
  console.log(
    `[copy-vendor] wrote ${path.relative(repoRoot, compatTarget)}`,
  );
}

const keptJs = new Set(["element.js", "compat.js"]);

function chunkImports(sourceCode) {
  const files = [];
  const pattern = /(?:import\(|from\s+)["'](\.\/[^"']+\.js)["']/g;
  for (const match of sourceCode.matchAll(pattern)) {
    files.push(match[1].slice(2));
  }
  return files;
}

const bundledChunks = new Set();
const pending = [code, ...(compatCode ? [compatCode] : [])];
while (pending.length > 0) {
  const sourceCode = pending.pop();
  if (!sourceCode) continue;
  for (const file of chunkImports(sourceCode)) {
    if (keptJs.has(file) || bundledChunks.has(file)) continue;
    const from = path.join(playerRoot, "dist", file);
    if (!fs.existsSync(from)) {
      console.error(`[copy-vendor] missing dist/${file}`);
      process.exit(1);
    }
    bundledChunks.add(file);
    pending.push(fs.readFileSync(from, "utf8"));
  }
}

for (const file of bundledChunks) {
  fs.copyFileSync(
    path.join(playerRoot, "dist", file),
    path.join(targetDir, file),
  );
  console.log(
    `[copy-vendor] wrote ${path.relative(repoRoot, path.join(targetDir, file))}`,
  );
}

for (const entry of fs.readdirSync(targetDir)) {
  if (!entry.endsWith(".js") || keptJs.has(entry) || bundledChunks.has(entry)) {
    continue;
  }
  fs.unlinkSync(path.join(targetDir, entry));
  console.log(`[copy-vendor] removed stale ${entry}`);
}

const wasmDir = path.join(playerRoot, "dist/wasm");
const targetWasmDir = path.join(targetDir, "wasm");
if (fs.existsSync(wasmDir)) {
  fs.mkdirSync(targetWasmDir, { recursive: true });
  for (const file of fs.readdirSync(wasmDir)) {
    fs.copyFileSync(path.join(wasmDir, file), path.join(targetWasmDir, file));
  }
}

const assetVersion = crypto
  .createHash("sha256")
  .update(code)
  .digest("hex")
  .slice(0, 8);

fs.mkdirSync(path.dirname(versionFile), { recursive: true });
fs.writeFileSync(
  versionFile,
  `// Generated by @nyumatflix/player copy:vendor — do not edit.\nexport const PLAYER_ASSET_VERSION = "${assetVersion}";\nexport const MOVI_PLAYER_ASSET_VERSION = PLAYER_ASSET_VERSION;\n`,
);

console.log(
  `[copy-vendor] wrote ${path.relative(repoRoot, target)} (v=${assetVersion})`,
);
