import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const playerRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(playerRoot, "../..");
const source = path.join(playerRoot, "dist/element.js");
const targetDir = path.join(repoRoot, "apps/web/public/vendor/player");
const target = path.join(targetDir, "element.js");
const versionFile = path.join(
  repoRoot,
  "apps/web/lib/player/player-asset.generated.ts",
);

if (!fs.existsSync(source)) {
  console.error("[copy-vendor] missing dist/element.js — run build first");
  process.exit(1);
}

const code = fs.readFileSync(source, "utf8");
fs.mkdirSync(targetDir, { recursive: true });
fs.writeFileSync(target, code);

const wasmDir = path.join(playerRoot, "dist/wasm");
const targetWasmDir = path.join(targetDir, "wasm");
if (fs.existsSync(wasmDir)) {
  fs.mkdirSync(targetWasmDir, { recursive: true });
  for (const file of fs.readdirSync(wasmDir)) {
    fs.copyFileSync(path.join(wasmDir, file), path.join(targetWasmDir, file));
  }
}

const assetVersion = crypto
  .createHash("sha256")
  .update(code)
  .digest("hex")
  .slice(0, 8);

fs.mkdirSync(path.dirname(versionFile), { recursive: true });
fs.writeFileSync(
  versionFile,
  `// Generated by @nyumatflix/player copy:vendor — do not edit.\nexport const PLAYER_ASSET_VERSION = "${assetVersion}";\nexport const MOVI_PLAYER_ASSET_VERSION = PLAYER_ASSET_VERSION;\n`,
);

console.log(
  `[copy-vendor] wrote ${path.relative(repoRoot, target)} (v=${assetVersion})`,
);
