#!/bin/sh
echo "🚀 Running pre-commit checks..."

npm run lint &
npm run test-ci &
npm run check-format &
npm run type-check &

wait
if [ $? -ne 0 ]; then
  echo "🚨 Pre-commit checks failed. Please fix the above issues before committing."
  exit 1
fi
