name: NyumatFlix CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the version of Node.js you're using for your project

      - name: Generate package-lock.json
        run: npm install

      - name: Clean install
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Check formatting
        run: npx prettier --check . --ignore-path .gitignore

      - name: Run lint
        run: npm run lint
