name: nyumatflix-ci

env:
  HUSKY: 0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: nyumatflix-v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create .env file
        run: |
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env.local

      - name: Build the app
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          NEXT_PUBLIC_TMDB_API_KEY: ${{ secrets.NEXT_PUBLIC_TMDB_API_KEY }}
        run: bun run build

      - name: Check formatting
        run: bunx prettier --check . --ignore-path .gitignore

      - name: Run lint
        run: bun run lint

      - name: Type check
        run: bun run type-check

      - name: Run tests
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          NEXT_PUBLIC_TMDB_API_KEY: ${{ secrets.NEXT_PUBLIC_TMDB_API_KEY }}
        run: bun run test-ci
