name: lint-nyumatflix

on:
  workflow_run:
    workflows: ["check-format-nyumatflix"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
